name: 'Composite Action'
description: 'User input'
inputs:
  who-to-greet: #id of the input
    description: 'who to greet'
    required: true
    default: 'Andrian'
outputs:
  name-of-repo:
    description: 'The name of repository'
    value: ${{ steps.repo_name.outputs.name-of-repo }}
runs:
  using: 'composite'
  steps:
    - name: Print the greetings
      run: |
        echo "Hi, $ENV_GREET."
        echo 'Thanks for accessing me.'
      shell: bash 
      env:
        ENV_GREET: ${{ inputs.who-to-greet }}

    - name: Repository name
      id: repo-name
      run: |
        echo "repo_name=${GITHUB_REPOSITORY}" >> $GITHUB_OUTPUT
      shell: bash